spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
#    url: jdbc:h2:tcp://localhost/~/jwp-subway-path;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug
