spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100 #최적화 옵션

server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
